services:
  postgres:
    image: postgres:17-alpine
    container_name: bank-db
    environment:
      - 'POSTGRES_DB=bank-db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./bank-app-db:/docker-entrypoint-initdb.d/
      - ./bank-app-db/data:/var/lib/postgresql/data